package pe.edu.upc.predictivemaintain.maintenance.interfaces.rest.resources;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import pe.edu.upc.predictivemaintain.maintenance.domain.model.valueobjects.SyncOperationType;

import java.time.Instant;
import java.util.UUID;

public record SyncOperationResource(
        @NotNull @Schema(description = "Generated by the app. Sending the same id twice never applies the action twice")
        UUID operationId,
        @NotNull UUID workOrderId,
        @NotNull @Schema(description = "START or COMPLETE") SyncOperationType type,
        @NotNull @Schema(description = "When the technician did it, by the device's clock") Instant performedAt,
        @Size(max = 2000) @Schema(description = "Corrective actions; required for COMPLETE") String summary) {
}