spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:predictivemaintain}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}