package pe.edu.upc.predictivemaintain.iam.interfaces.rest.resources;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.util.UUID;

public record RegisterCompanyResource(
        @NotBlank String companyName,
        @NotBlank String email,
        @NotBlank String password,
        @NotNull
        @Schema(description = "UUID generated by the client; repeating it makes the registration idempotent")
        UUID registrationId) {
}